### ISSUE TITLE
Kontrolle Aufgabe 03

### ISSUE THREAD

**Issue by MelvinBusch** [mtmatern/EIA2#1]
1. AD's sind etwas knapp, könnten ausführlicher sein.
2. Event-Listener zur besseren Übersicht möglichst weit oben im Code platzieren.
3. Kein `window.onload` verwenden. Stattdessen lieber einen Event-Listener installieren.
4. Bitte noch keine anonymen Funktionen verwenden.
5. Ansonsten in Ordnung 👍🏻

_14.04 | 23:39 (mb)_

**Comment by Plagiatus** [comment]
Bitte niemals anonyme Funktionen verwenden. War explizit in der Aufgabe so gefordert!

**Comment by Plagiatus** [comment]
Außerdem zu viele Variablen nicht typisiert.

**Comment by MelvinBusch** [comment]
Verteidigt (mb)
